baseurl = "https://blog.delicacy.top/"  # please update this to your actual URL
languageCode = "en-us"
title = "Bugfly66's Blog"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
notes = "/notes/:year/:month/:day/:slug/"
posts = "/posts/:year/:month/:day/:slug/"

[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 2

[[menu.main]]
name = "Categories"
url = "categories/"
weight = 3

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 4

[[menu.main]]
name = "Subscribe"
url = "index.xml"

[params]
description = "A website built through Hugo and blogdown."
footer = "&copy; [bugfly66](https://blog.delicacy.top) 2025 -- {Year} | [Github](https://github.com/bugfly66) | [Email](mailto:bugfly66)"

[markup.highlight]
codeFences = true 

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters = { block = [ ["$$", "$$"], ["[", "["] ], inline = [ ["$", "$"] ] }
